 驱动器 D 中的卷是 新加卷
 卷的序列号是 32AC-75D1

 D:\KinSeal_PC\KinSealStudio-build-desktop\debug\Link\serial\Custom 的目录

2015/08/05  19:57    <DIR>          .
2015/08/05  19:57    <DIR>          ..
2010/06/02  14:13                19 dir.BAT
2015/08/05  19:57                 0 aaa.inc
2015/05/20  14:19               678 Custom_Null.ini
2015/05/20  14:20               685 Custom_Penetrate.ini
               4 个文件          1,382 字节
               2 个目录 219,435,778,048 可用字节
